### ISSUE TITLE
run example.py problem

### ISSUE THREAD

**Issue by ShanyChen** [refelix/network_3d#1]
Hi, 
I run example.py and it goes like this.
Exception occurred in traits notification handler for object: <mayavi.tools.filters.SetActiveAttributeFactory object at 0x0000019FA6B23678>, trait: point_scalars, old value: , new value: scalars
Traceback (most recent call last):
  File "F:\python\lib\site-packages\traits\trait_notifiers.py", line 394, in __call__
    self.handler(*args)
  File "F:\python\lib\site-packages\mayavi\tools\pipe_base.py", line 202, in _anytrait_changed
    setattr(obj, components[-1], value)
  File "F:\python\lib\site-packages\mayavi\core\trait_defs.py", line 97, in set_value
    raise TraitError(object, name,"one of %s"%values, value)
traits.trait_errors.TraitError: The 'point_scalars_name' trait of a SetActiveAttribute instance must be one of [''], but a value of 'scalars' <class 'str'> was specified.
Traceback (most recent call last):
  File "E:/vessel/network_3d-master/example.py", line 35, in <module>
    plot_graph(G)
  File "E:\vessel\network_3d-master\network_3d.py", line 452, in plot_graph
    tubes, point_scalars='scalars'), colormap=edge_colormap, color=edge_color, **kwargs)
  File "F:\python\lib\site-packages\mayavi\tools\pipe_base.py", line 38, in the_function
    factory = factory_class(*args, **kwargs)
  File "F:\python\lib\site-packages\mayavi\tools\pipe_base.py", line 163, in __init__
    self.trait_set(**traits)
  File "F:\python\lib\site-packages\mayavi\tools\pipe_base.py", line 184, in trait_set
    self._anytrait_changed(trait, value)
  File "F:\python\lib\site-packages\mayavi\tools\pipe_base.py", line 202, in _anytrait_changed
    setattr(obj, components[-1], value)
  File "F:\python\lib\site-packages\mayavi\core\trait_defs.py", line 97, in set_value
    raise TraitError(object, name,"one of %s"%values, value)
traits.trait_errors.TraitError: The 'point_scalars_name' trait of a SetActiveAttribute instance must be one of [''], but a value of 'scalars' <class 'str'> was specified.

Process finished with exit code 1

I don't konw why. Please help me.

**Comment by refelix** [comment]
Hi, I guess it has to do with the versions of your libraries and even the Python version. The time I wrote the stuff I was using Python 2.7. I guess you tried to make it run on Python 3.x? Some fundamental changes concerning iterators changed. I made some changes to adopt it to Python3. Let me know if it did the trick.
